### ISSUE TITLE
NPE in GregorianChronology$.getInstance

### ISSUE THREAD

**Issue by mkotsbak** [mdedetrich/soda-time#6]
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.joda.time.chrono.ISOChronology$.<init>(ISOChronology.scala:17)
    at org.joda.time.chrono.ISOChronology$.<clinit>(ISOChronology.scala)
    at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.scala:22)
    at org.joda.time.DateTime.<init>(DateTime.scala:136)
    at org.joda.time.DateTime$.now(DateTime.scala:17)
[...]
Caused by: java.lang.NullPointerException
    at org.joda.time.chrono.GregorianChronology$.getInstance(GregorianChronology.scala:33)
    at org.joda.time.chrono.GregorianChronology$.getInstance(GregorianChronology.scala:25)
    at org.joda.time.chrono.GregorianChronology$.<init>(GregorianChronology.scala:17)
    at org.joda.time.chrono.GregorianChronology$.<clinit>(GregorianChronology.scala)

It fails at line DateTime.now().minusDays(10)

Isn't that how it is supposed to be used?

**Comment by mdedetrich** [comment]
Yeah there is currently an issue regarding initialisation, I have asked a question at SO here http://stackoverflow.com/questions/36825352/uninitialized-fields-inside-an-object

No idea why this is happening tbh

**Comment by mkotsbak** [comment]
Could it help to make it lazy?

**Comment by mdedetrich** [comment]
This specific issue has been closed, however there are more null errors which need to be looked at
